#! /usr/bin/env bash

source "${HOMEgfs}/ush/preamble.sh"
source "${HOMEgfs}/ush/jjob_header.sh" -e "bufr_sounding_collect" -c "base bufr_sounding_collect"

########################################
# Runs GFS BUFR SOUNDINGS
########################################

export model=${model:-gfs}
export SENDDBN=${SENDDBN:-YES}
export DBNROOT=${DBNROOT:-${UTILROOT}/fakedbn}

##############################
# Define COM Directories
##############################
YMD=${PDY} HH=${cyc} declare_from_tmpl -rx COM_ATMOS_BUFR

[[ ! -d ${COM_ATMOS_BUFR} ]] && mkdir -p "${COM_ATMOS_BUFR}"

########################################################
# Execute the script.
"${SCRgfs}/exgfs_atmos_bufr_sounding_collect.sh"
status=$?
[[ ${status} -ne 0 ]] && exit "${status}"


##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]] ; then
  cat "${pgmout}"
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || exit 0
[[ ${KEEPDATA} = "NO" ]] && rm -rf "${DATA}"


exit 0

