#! /usr/bin/env bash

source "${HOMEgfs}/ush/preamble.sh"


##############################################
# make temp directory
##############################################
export DATA=${DATA:-${DATAROOT}/${jobid}}
mkdir -p "${DATA}"
cd "${DATA}" || exit 1


##############################################
# Run setpdy and initialize PDY variables
##############################################
export cycle="t${cyc}z"
setpdy.sh
. ./PDY


##############################################
# Determine Job Output Name on System
##############################################
export pid=${pid:-$$}
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile


#############################
# Source relevant config files
#############################
export EXPDIR=${EXPDIR:-${HOMEgfs}/parm/config}
configs="base post"
for config in ${configs}; do
    . ${EXPDIR}/config.${config}
    status=$?
    (( status != 0 )) && exit "${status}"
done


##########################################
# Source machine runtime environment
##########################################
. "${HOMEgfs}/env/${machine}.env" post
status=$?
(( status != 0 )) && exit "${status}"


####################################
# Specify version numbers
####################################
export crtm_ver=${post_crtm_ver:-v2.2.6}
export gfs_ver=${gfs_ver:-v15.0.0}
export hwrf_ver=${hwrf_ver:-v11.0.5}
export g2tmpl_ver=${g2tmpl_ver:-v1.5.0}

##############################################
# Set variables used in the exglobal script
##############################################
export CDATE=${CDATE:-${PDY}${cyc}}
export CDUMP=${CDUMP:-${RUN:-"gfs"}}
export COMPONENT="atmos"


##############################################
# TODO: Remove this egregious HACK
##############################################
if [[ "${SDATE:-}" = "${CDATE}" ]]; then
  if [[ ${post_times} = "anl" ]]; then
    echo "No offline post-processing in the first half cycle for analysis"
    exit 0
  fi
fi


##############################################
# Begin JOB SPECIFIC work
##############################################
export APRUNP=${APRUN:-${APRUN_NP}}
export RERUN=${RERUN:-NO}

export PARMpost=${PARMpost:-${HOMEgfs}/parm/post}
# export INLINE_POST=${WRITE_DOPOST:-".false."}

export COMIN=${COMIN:-${ROTDIR}/${RUN}.${PDY}/${cyc}/atmos}
export COMOUT=${COMOUT:-${ROTDIR}/${RUN}.${PDY}/${cyc}/atmos}

# shellcheck disable=SC2174
[[ ! -d "${COMOUT}" ]] && mkdir -m 775 -p "${COMOUT}"
# shellcheck disable=

###############################################################
# Run relevant exglobal script
###############################################################
"${HOMEgfs}/scripts/exglobal_atmos_post.sh"
status=$?
if (( status != 0 )); then
  exit "${status}"
fi  

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [ -e "${pgmout}" ]; then
  cat "${pgmout}"
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || exit 1
[[ "${KEEPDATA:-NO}" = "NO" ]] && rm -rf "${DATA}"


exit 0
