#! /usr/bin/env bash

export STRICT=NO
source "${HOMEgfs}/ush/preamble.sh"

export DATAjob="${DATAROOT}/${RUN}jediinline.${PDY:-}${cyc}"
export DATA="${DATAjob}/${jobid}"
source "${HOMEgfs}/ush/jjob_header.sh" -e "jediinline" -c "base jediinline"

#export GDASsorc=/scratch1/NCEPDEV/nems/David.Burrows/feb4_mark_updates/gw_jedi_soca_uwtools_update/sorc/gdas.cd
export GDASsorc=${HOMEgfs}/sorc/gdas.cd
export JEDIIN=/scratch1/NCEPDEV/nems/David.Burrows/jedi_input

unset PYTHONPATH
source ${GDASsorc}/bundle/venv/uwtools/bin/activate

cp -r ${JEDIIN}/gen-exp ${DATA}
chmod 766 ${DATA}/gen-exp
cd ${DATA}/gen-exp

rm -f Data/crtm/*
cp -r ${JEDIIN}/2.3.0/* Data/crtm/
cp -r ${JEDIIN}/AerosolCoeff.bin Data/crtm/AerosolCoeff.bin

python ${HOMEgfs}/scripts/exjedi_inline.py
export err=$?;
if [ ${err} -ne 0 ]; then exit 1; fi

deactivate

###############################################################
# Run relevant exglobal script
###############################################################
"${FORECASTSH:-${SCRgfs}/exjedi_inline.sh}"
status=$?
(( status != 0 )) && exit "${status}"
##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]] ; then
  cat "${pgmout}"
fi

##########################################
# Remove the Temporary working directory
##########################################
#cd "${DATAROOT}" || true
## do not remove DATAjob. It contains DATAoutput
#if [[ "${KEEPDATA}" == "NO" ]]; then
#  rm -rf "${DATA}"
#
#  # Determine if this is the last segment
#  commas="${FCST_SEGMENTS//[^,]}"
#  n_segs=${#commas}
#  if (( n_segs - 1 == ${FCST_SEGMENT:-0} )); then
#    # Only delete temporary restarts if it is the last segment
#    rm -rf "${DATArestart}"
#  fi
#fi

exit 0
